# Exercici 1

In [17]:
import numpy as np 

arr = np.array([1, 2, 3, 4, 5, 5])

print(np.mean(arr))
print(np.median(arr))
print(np.min(arr))
print(np.max(arr))
if np.size(np.shape(arr))>1:
    print("Error!")

1
3.3333333333333335
3.5
1
5


# Exercici 2

In [19]:
from numpy import random

x = random.randint(100, size=(5, 5))

print(x) 

[[ 8 77 18  1 87]
 [39  6 99 82 37]
 [52 69 50 83 56]
 [35 59 55  7 90]
 [20 91 24 63 13]]


# Exercici 3

In [28]:
x = random.randint(100, size=(2, 5))
print(x)
print(np.sum([x[0],x[1]], axis=1))
print(x[0]+x[1])

[[51 23 99 89  5]
 [98 77 43 40 62]]
[267 320]
[149 100 142 129  67]


# Exercici 4

In [34]:
from scipy import stats

x = [5,7,8,7,2,17,2,9,4,11,12,9,6]
y = [99,86,87,88,111,86,103,87,94,78,77,85,86]

slope, intercept, r, p, std_err = stats.linregress(x, y)

print(r)

-0.7585915243761551
